### PR TITLE
Various fixes for beta

### LINKED ISSUE #495: Regenerate and render causes focus even if it didn't have it before
#### React-Quill version 
- [x] master
- [x] 1.3.3

Similar to this [issue](https://github.com/zenoamaro/react-quill/issues/317) "How to disable auto focus when quill render?". But it looks to be a different cause. 

It appears to be happening in the `regenerate` logic [here](https://github.com/zenoamaro/react-quill/blob/master/src/component.js#L210). This is calling `focus()` even though it may not have had it to start with.

### PR DESCRIPTION
**Pull request by rockwotj**
Fixes #495 

It seems that in aa9759742f24f49bc651b1d65fd0e08b4f349d62 this if statement is actually needed. If setSelection is called with `null` then quill explicitly removes focus from *any* element on the screen. So in my usecase typing in another element becomes unfocused after each keystroke due to this.

/cc @jwngr

### CODE REVIEW

**Comment by rockwotj** [comment]
This also fixes an issue where postpone is trying to access the editor, but by the time it runs the editor has been destroyed

**Comment by rockwotj** [comment]
We also ran into a couple points where the component was unmounted while there was no editor, so I've made a couple methods fail gracefully instead

**Comment by rockwotj** [comment]
I have not yet triggered this issue from setEditorContents. Possibly because I'm using uncontrolled mode? I can guard this section as well.

File: src/index.tsx [hunk 1]
```diff
@@ -277,8 +277,9 @@ class ReactQuill extends React.Component<ReactQuillProps, ReactQuillState> {
       const {delta, selection} = this.regenerationSnapshot!;
       delete this.regenerationSnapshot;
       this.instantiateEditor();
-      this.editor!.setContents(delta);
-      if (selection) postpone(() => this.editor!.setSelection(selection));
+      const editor = this.editor!;
+      editor.setContents(delta);
+      if (selection) postpone(() => editor.setSelection(selection));
```
Comment (zenoamaro) [inline src/index.tsx:282]: I think this can be converted to use `this.setEditorSelection` with no particular ill effects. Can you verify?

Comment (rockwotj) [reply src/index.tsx:282]: It works fine for my usecase.

What was the reason for using postpone here? I wonder if it's possible for the selection to "jump back" if there is text inserted between the time setContents is called and the time the selection is applied. Although that race seems unlikely 🤔

Comment (zenoamaro) [reply src/index.tsx]: > What was the reason for using postpone here? 

Controlled-mode Quill blurs the editor in the micro-tick immediately after `setContents`. Postponing this code allows overriding that blur. I wasn't able to find a deeper cause yet, and this solved the issue for controlled mode.

> I wonder if it's possible for the selection to "jump back" if there is text inserted between the time setContents is called and the time the selection is applied. Although that race seems unlikely 🤔
 
The race is unlikely as it happens in the very next micro-tick, and is queued before user code has a chance to run.

If `postpone -> this.setEditorSelection` works, let's use that, and unify the approaches. Worst case we will have a reproduction case showing us why not.

Other than this, it can get merged for me 👍 thanks a lot for the excellent work

**Comment by zenoamaro** [comment]
Great work! Thanks a lot!
